// Copyright 2024 Sherlock Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package hosts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// Export exports hosts data to the specified format.
func (m *Manager) Export(ctx context.Context, format ExportFormat) ([]byte, error) {
	hosts, err := m.ListHosts(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to list hosts: %w", err)
	}

	groups, err := m.ListGroups(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list groups: %w", err)
	}

	tags, err := m.ListTags(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list tags: %w", err)
	}

	data := ExportData{
		Version: "1.0",
		Hosts:   make([]ExportedHost, 0, len(hosts)),
		Groups:  make([]ExportedGroup, 0, len(groups)),
		Tags:    make([]ExportedTag, 0, len(tags)),
	}

	// Convert hosts
	for _, h := range hosts {
		eh := ExportedHost{
			Host:        h.Host,
			Port:        h.Port,
			User:        h.User,
			Alias:       h.Alias,
			Description: h.Description,
		}

		// Get groups
		for _, g := range h.Groups {
			eh.Groups = append(eh.Groups, g.Name)
		}

		// Get tags
		for _, t := range h.Tags {
			eh.Tags = append(eh.Tags, t.Name)
		}

		// Get env vars
		envVars, _ := m.GetEnvVars(ctx, h.ID)
		if len(envVars) > 0 {
			eh.EnvVars = envVars
		}

		data.Hosts = append(data.Hosts, eh)
	}

	// Convert groups
	for _, g := range groups {
		data.Groups = append(data.Groups, ExportedGroup{
			Name:        g.Name,
			Description: g.Description,
		})
	}

	// Convert tags
	for _, t := range tags {
		data.Tags = append(data.Tags, ExportedTag{
			Name:  t.Name,
			Color: t.Color,
		})
	}

	switch format {
	case ExportJSON:
		return json.MarshalIndent(data, "", "  ")
	case ExportYAML:
		return yaml.Marshal(data)
	case ExportSSHConfig:
		return m.exportSSHConfig(data)
	default:
		return nil, fmt.Errorf("unsupported export format: %s", format)
	}
}

// exportSSHConfig exports hosts in SSH config format.
func (m *Manager) exportSSHConfig(data ExportData) ([]byte, error) {
	var sb strings.Builder

	sb.WriteString("# Sherlock SSH Config Export\n")
	sb.WriteString("# Generated by Sherlock\n\n")

	for _, h := range data.Hosts {
		hostName := h.Alias
		if hostName == "" {
			hostName = fmt.Sprintf("%s_%s_%d", h.User, h.Host, h.Port)
		}

		sb.WriteString(fmt.Sprintf("Host %s\n", hostName))
		sb.WriteString(fmt.Sprintf("    HostName %s\n", h.Host))
		sb.WriteString(fmt.Sprintf("    User %s\n", h.User))
		sb.WriteString(fmt.Sprintf("    Port %d\n", h.Port))

		if h.Description != "" {
			sb.WriteString(fmt.Sprintf("    # %s\n", h.Description))
		}

		sb.WriteString("\n")
	}

	return []byte(sb.String()), nil
}

// Import imports hosts data from the specified format.
func (m *Manager) Import(ctx context.Context, rawData []byte, format ExportFormat) error {
	var data ExportData

	switch format {
	case ExportJSON:
		if err := json.Unmarshal(rawData, &data); err != nil {
			return fmt.Errorf("failed to parse JSON: %w", err)
		}
	case ExportYAML:
		if err := yaml.Unmarshal(rawData, &data); err != nil {
			return fmt.Errorf("failed to parse YAML: %w", err)
		}
	default:
		return fmt.Errorf("unsupported import format: %s", format)
	}

	// Import groups first
	for _, g := range data.Groups {
		existing, _ := m.GetGroupByName(ctx, g.Name)
		if existing != nil {
			continue // Skip existing groups
		}
		group := &Group{Name: g.Name, Description: g.Description}
		if err := m.CreateGroup(ctx, group); err != nil {
			// Ignore duplicate errors
		}
	}

	// Import tags
	for _, t := range data.Tags {
		existing, _ := m.GetTagByName(ctx, t.Name)
		if existing != nil {
			continue // Skip existing tags
		}
		tag := &Tag{Name: t.Name, Color: t.Color}
		if err := m.CreateTag(ctx, tag); err != nil {
			// Ignore duplicate errors
		}
	}

	// Import hosts
	for _, h := range data.Hosts {
		// Check if host already exists
		existing, _ := m.GetHostByHostKey(ctx, h.Host, h.Port, h.User)
		var hostID int64

		if existing != nil {
			hostID = existing.ID
			// Update alias and description if set
			if h.Alias != "" && existing.Alias == "" {
				existing.Alias = h.Alias
			}
			if h.Description != "" && existing.Description == "" {
				existing.Description = h.Description
			}
			_ = m.UpdateHost(ctx, existing)
		} else {
			// Create new host
			host := &Host{
				Host:        h.Host,
				Port:        h.Port,
				User:        h.User,
				Alias:       h.Alias,
				Description: h.Description,
			}
			if err := m.AddHost(ctx, host); err != nil {
				continue
			}
			hostID = host.ID
		}

		// Add to groups
		for _, groupName := range h.Groups {
			_ = m.AddHostToGroupByName(ctx, hostID, groupName)
		}

		// Add tags
		for _, tagName := range h.Tags {
			_ = m.AddTagToHostByName(ctx, hostID, tagName)
		}

		// Set env vars
		for name, value := range h.EnvVars {
			_ = m.SetEnvVar(ctx, hostID, name, value)
		}
	}

	return nil
}
